# Generated by Django 5.1.7 on 2025-03-31 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Enter your title')),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 3, 31, 13, 19, 59, 927354, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
