# Generated by Django 5.2 on 2025-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=50)),
                ('reciepe_description', models.TextField(max_length=500)),
                ('receipe_ingre', models.CharField(max_length=500)),
            ],
        ),
    ]
